#!/bin/sh
#
# Start the USB devices
#

case "$1" in
  start)
	echo "Turn on USB devices..."
	modprobe musb_hdrc
	modprobe davinci
	modprobe udc_core
	modprobe g_ether
	#modprobe g_serial
	;;
  stop)
	echo -n "Stopping USB devices..."
	#rmmod g_serial
	rmmod g_ether
	rmmod udc_core
	rmmod davinci
	rmmod musb_hdrc
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
